// This file is generated by Slice Machine. Update with care!

import HomeSlider from './HomeSlider';
import ImageBlock from './ImageBlock';
import SliderBlock from './SliderBlock';
import TextBlock from './TextBlock';
import VideoBlock from './VideoBlock';

export {
	HomeSlider,
	ImageBlock,
	SliderBlock,
	TextBlock,
	VideoBlock,
};

export const components = {
	home_slider: HomeSlider,
	image_block: ImageBlock,
	slider_block: SliderBlock,
	text_block: TextBlock,
	video_block: VideoBlock,
};
