// This file is generated by Prismic local builder. Update with care!

export { default as HomeSlider } from './HomeSlider'
export { default as ImageBlock } from './ImageBlock'
export { default as SliderBlock } from './SliderBlock'
export { default as TextBlock } from './TextBlock'
